services:
  backend:
    build: ./candle
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:9.5.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: candle
      MYSQL_USER: 'root'
    ports:
      - "3000:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
